// WASM client wrapper with type-safe interface

import type {
  AuthContext,
  CreateDotOutput,
  CreateLinkOutput,
  DotDraft,
  Dot,
  GrantAccessOutput,
  LinkGrants,
  LinkType,
  ScopeId,
  Timestamp,
  UserId,
  VisibilityGrant,
  WasmResult,
  CanViewDotOutput,
  FilterVisibleDotsOutput,
  Link,
} from "./types";
import { unwrapWasmResult } from "./types";

// Type definitions for the WASM module exports
// These will be generated by wasm-bindgen
export interface DotrcWasm {
  core_version(): string;
  wasm_create_dot(draftJson: string, now: string, dotId: string): string;
  wasm_grant_access(
    dotJson: string,
    existingGrantsJson: string,
    targetUsersJson: string,
    targetScopesJson: string,
    contextJson: string,
    now: string
  ): string;
  wasm_create_link(
    fromDotJson: string,
    toDotJson: string,
    linkType: string,
    grantsJson: string,
    existingLinksJson: string,
    contextJson: string,
    now: string
  ): string;
  wasm_can_view_dot(
    dotJson: string,
    grantsJson: string,
    contextJson: string
  ): string;
  wasm_filter_visible_dots(
    dotsJson: string,
    grantsJson: string,
    contextJson: string
  ): string;
}

/**
 * Type-safe wrapper around dotrc-core WASM exports.
 * Handles JSON serialization/deserialization and error handling.
 */
export class DotrcCore {
  constructor(private wasm: DotrcWasm) {}

  /**
   * Get the core version
   */
  version(): string {
    return this.wasm.core_version();
  }

  /**
   * Create a new dot from a draft
   *
   * @param draft - The dot draft to create
   * @param now - Current timestamp (RFC3339)
   * @param dotId - Unique ID for the dot (generated by adapter)
   * @returns The created dot, visibility grants, and any links
   * @throws {DotrcError} If validation or authorization fails
   */
  createDot(draft: DotDraft, now: Timestamp, dotId: string): CreateDotOutput {
    const resultJson = this.wasm.wasm_create_dot(
      JSON.stringify(draft),
      now,
      dotId
    );
    const result: WasmResult<CreateDotOutput> = JSON.parse(resultJson);
    return unwrapWasmResult(result);
  }

  /**
   * Grant access to an existing dot
   *
   * @param dot - The dot to grant access to
   * @param existingGrants - Current visibility grants for the dot
   * @param targetUsers - User IDs to grant access to
   * @param targetScopes - Scope IDs to grant access to
   * @param context - Authorization context for the requesting user
   * @param now - Current timestamp (RFC3339)
   * @returns New visibility grants to persist
   * @throws {DotrcError} If authorization fails or validation fails
   */
  grantAccess(
    dot: Dot,
    existingGrants: VisibilityGrant[],
    targetUsers: UserId[],
    targetScopes: ScopeId[],
    context: AuthContext,
    now: Timestamp
  ): GrantAccessOutput {
    const resultJson = this.wasm.wasm_grant_access(
      JSON.stringify(dot),
      JSON.stringify(existingGrants),
      JSON.stringify(targetUsers),
      JSON.stringify(targetScopes),
      JSON.stringify(context),
      now
    );
    const result: WasmResult<GrantAccessOutput> = JSON.parse(resultJson);
    return unwrapWasmResult(result);
  }

  /**
   * Create a link between two dots
   *
   * @param fromDot - Source dot
   * @param toDot - Target dot
   * @param linkType - Type of link relationship
   * @param grants - Visibility grants for both dots
   * @param existingLinks - Current links to check for duplicates
   * @param context - Authorization context for the requesting user
   * @param now - Current timestamp (RFC3339)
   * @returns The created link
   * @throws {DotrcError} If authorization fails, dots are in different tenants, or link already exists
   */
  createLink(
    fromDot: Dot,
    toDot: Dot,
    linkType: LinkType,
    grants: LinkGrants,
    existingLinks: Link[],
    context: AuthContext,
    now: Timestamp
  ): CreateLinkOutput {
    const resultJson = this.wasm.wasm_create_link(
      JSON.stringify(fromDot),
      JSON.stringify(toDot),
      linkType,
      JSON.stringify(grants),
      JSON.stringify(existingLinks),
      JSON.stringify(context),
      now
    );
    const result: WasmResult<CreateLinkOutput> = JSON.parse(resultJson);
    return unwrapWasmResult(result);
  }

  /**
   * Check if a user can view a dot
   *
   * @param dot - The dot to check
   * @param grants - Visibility grants for the dot
   * @param context - Authorization context for the requesting user
   * @returns True if the user can view the dot
   */
  canViewDot(
    dot: Dot,
    grants: VisibilityGrant[],
    context: AuthContext
  ): boolean {
    const resultJson = this.wasm.wasm_can_view_dot(
      JSON.stringify(dot),
      JSON.stringify(grants),
      JSON.stringify(context)
    );
    const result: WasmResult<CanViewDotOutput> = JSON.parse(resultJson);
    return unwrapWasmResult(result).can_view;
  }

  /**
   * Filter a list of dots to only those visible to the user
   *
   * @param dots - List of dots to filter
   * @param grants - Visibility grants for all dots
   * @param context - Authorization context for the requesting user
   * @returns Filtered list of visible dots
   */
  filterVisibleDots(
    dots: Dot[],
    grants: VisibilityGrant[],
    context: AuthContext
  ): Dot[] {
    const resultJson = this.wasm.wasm_filter_visible_dots(
      JSON.stringify(dots),
      JSON.stringify(grants),
      JSON.stringify(context)
    );
    const result: WasmResult<FilterVisibleDotsOutput> = JSON.parse(resultJson);
    return unwrapWasmResult(result).dots;
  }
}
